-- ==============================================================================
-- deploy_all.sql (DEPRECATED)
-- ==============================================================================
-- ATENÇÃO: Este script foi descontinuado.
-- O caminho oficial para aplicar migrations no ambiente remoto é utilizando a
-- CLI oficial do Supabase:
--
--     supabase db push
--
-- As migrations utilizam sintaxe que depende da ordem de execução, 
-- e o comando \ir não é suportado pelo painel SQL do Supabase. 
-- Para resetar localmente use:
--
--     supabase db reset
-- ==============================================================================
