name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-db:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase local development
        run: supabase start

      - name: Reset Database
        run: supabase db reset

      - name: Lint Database
        run: supabase db lint

      - name: Run pgTAP tests
        run: supabase test db
